const SET_BOARD_FIELDS = 'SET_BOARD_FIELDS';
const BOARD_FIELD_COUNTER_INCREMENT = 'BOARD_FIELD_COUNTER_INCREMENT';
const BOARD_PLAYER_SCORE_INCREMENT = 'BOARD_PLAYER_SCORE_INCREMENT';
const BOARD_PC_SCORE_INCREMENT = 'BOARD_PC_SCORE_INCREMENT';
const BOARD_RESET = 'BOARD_RESET';

export {
  SET_BOARD_FIELDS,
  BOARD_FIELD_COUNTER_INCREMENT,
  BOARD_PLAYER_SCORE_INCREMENT,
  BOARD_PC_SCORE_INCREMENT,
  BOARD_RESET
};
